/**
 * Standalone production server for Roundhouse.
 *
 * Two responsibilities:
 *
 * 1. Serve the Progressive Web App at `/` for browsers. The web bundle
 *    is generated by `expo export --platform web` into
 *    `static-build/web/` during the build step. Browsers (iOS Safari,
 *    Android Chrome, desktop) get the actual app — not a landing page.
 *    Any unknown path falls back to `index.html` so client-side routing
 *    (Expo Router) works on direct URL hits and on refresh.
 *
 * 2. Serve Expo Go manifests for iOS/Android devices that include the
 *    `expo-platform` request header. Each platform gets its own manifest
 *    (`static-build/{ios,android}/manifest.json`) which references a
 *    timestamped JS bundle under `static-build/{timestamp}/_expo/...`.
 *    This is how phones running Expo Go can load the production build
 *    without going through the App Store.
 *
 * Zero external dependencies — uses only Node.js built-ins (http, fs, path).
 */

const http = require("http");
const fs = require("fs");
const path = require("path");

const STATIC_ROOT = path.resolve(__dirname, "..", "static-build");
const WEB_ROOT = path.join(STATIC_ROOT, "web");
const basePath = (process.env.BASE_PATH || "/").replace(/\/+$/, "");

const MIME_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".webmanifest": "application/manifest+json; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".map": "application/json",
};

function serveManifest(platform, res) {
  const manifestPath = path.join(STATIC_ROOT, platform, "manifest.json");

  if (!fs.existsSync(manifestPath)) {
    res.writeHead(404, { "content-type": "application/json" });
    res.end(
      JSON.stringify({ error: `Manifest not found for platform: ${platform}` }),
    );
    return;
  }

  const manifest = fs.readFileSync(manifestPath, "utf-8");
  res.writeHead(200, {
    "content-type": "application/json; charset=utf-8",
    "cache-control": "no-store",
  });
  res.end(manifest);
}

function safeJoin(root, urlPath) {
  // Strip leading slash so path.join doesn't reset the root.
  const safe = path.normalize(urlPath).replace(/^(\.\.(\/|\\|$))+/, "");
  const full = path.join(root, safe);
  return full.startsWith(root) ? full : null;
}

function serveFile(filePath, res) {
  const ext = path.extname(filePath).toLowerCase();
  const contentType = MIME_TYPES[ext] || "application/octet-stream";
  const content = fs.readFileSync(filePath);

  // The web bundle's hashed assets (under /_expo/) are content-addressed
  // and safe to cache aggressively. HTML and the PWA manifest must stay
  // fresh so updates are picked up on the next visit.
  const isHashedAsset =
    filePath.includes(`${path.sep}_expo${path.sep}`) ||
    filePath.includes(`${path.sep}assets${path.sep}`);
  const cacheControl = isHashedAsset
    ? "public, max-age=31536000, immutable"
    : "public, max-age=0, must-revalidate";

  res.writeHead(200, {
    "content-type": contentType,
    "cache-control": cacheControl,
  });
  res.end(content);
}

function tryServeStatic(root, urlPath, res) {
  const filePath = safeJoin(root, urlPath);
  if (!filePath) return false;
  if (!fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) {
    return false;
  }
  serveFile(filePath, res);
  return true;
}

function serveWebAppFallback(res) {
  // Try a route-specific HTML first (Expo Router static export emits
  // one per route), then fall back to the root index for client-side
  // routes that weren't pre-rendered.
  const indexHtml = path.join(WEB_ROOT, "index.html");
  if (fs.existsSync(indexHtml)) {
    serveFile(indexHtml, res);
    return;
  }
  res.writeHead(404, { "content-type": "text/plain" });
  res.end("Not Found");
}

const server = http.createServer((req, res) => {
  const url = new URL(req.url || "/", `http://${req.headers.host}`);
  let pathname = url.pathname;

  if (basePath && pathname.startsWith(basePath)) {
    pathname = pathname.slice(basePath.length) || "/";
  }

  // Expo Go: phones running the dev client / Expo Go app send the
  // `expo-platform` header when fetching `/` or `/manifest`. Hand them
  // their platform manifest so they can boot the JS bundle.
  const platform = req.headers["expo-platform"];
  if (
    (pathname === "/" || pathname === "/manifest") &&
    (platform === "ios" || platform === "android")
  ) {
    return serveManifest(platform, res);
  }

  // Browser at "/" — serve the PWA shell.
  if (pathname === "/") {
    return serveWebAppFallback(res);
  }

  // 1) Try the web bundle root (this also covers /manifest.webmanifest,
  //    /apple-touch-icon.png, /favicon.ico — everything in `public/` got
  //    copied here by `expo export`).
  if (tryServeStatic(WEB_ROOT, pathname, res)) return;

  // 2) Try the timestamped Expo Go bundle / asset paths.
  if (tryServeStatic(STATIC_ROOT, pathname, res)) return;

  // 3) Client-side route — let Expo Router handle it.
  serveWebAppFallback(res);
});

const port = parseInt(process.env.PORT || "3000", 10);
server.listen(port, "0.0.0.0", () => {
  console.log(`Serving Roundhouse on port ${port}`);
});
