import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import propertiesRouter from "./properties";
import propertyKnowledgeRouter from "./property-knowledge";
import logsRouter from "./logs";
import messagesRouter from "./messages";
import notificationsRouter from "./notifications";
import workOrdersRouter from "./work-orders";
import standardsRouter from "./standards";
import storageRouter from "./storage";
import assetsRouter from "./assets";
import discoveryRouter from "./discovery";
import invitesRouter from "./invites";
import appInvitesRouter from "./app-invites";
import rewardsRouter from "./rewards";
import outwardAccountsRouter from "./outward-accounts";
import billingRouter from "./billing";
import teamSeatsRouter from "./team-seats";
import adminRouter from "./admin";
import remindersRouter from "./reminders";
import questionsRouter from "./questions";
import companyNoticesRouter from "./companyNotices";
import gameRoomRouter from "./game-room";
import presetChipsRouter from "./preset-chips";
import adminDemoProfilesRouter from "./admin-demo-profiles";
import entitiesRouter from "./entities";
import conciergeRouter from "./concierge";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(propertiesRouter);
router.use(propertyKnowledgeRouter);
router.use(logsRouter);
router.use(messagesRouter);
router.use(notificationsRouter);
router.use(workOrdersRouter);
router.use(standardsRouter);
router.use(storageRouter);
router.use(assetsRouter);
router.use(discoveryRouter);
router.use(invitesRouter);
router.use(appInvitesRouter);
router.use(rewardsRouter);
router.use(outwardAccountsRouter);
router.use(billingRouter);
router.use(teamSeatsRouter);
router.use(adminRouter);
router.use(remindersRouter);
router.use(questionsRouter);
router.use(companyNoticesRouter);
router.use(gameRoomRouter);
router.use(presetChipsRouter);
router.use(adminDemoProfilesRouter);
router.use(entitiesRouter);
router.use(conciergeRouter);

export default router;
